require: rubocop-minitest

AllCops:
  TargetRubyVersion: 2.7
  NewCops: enable
  SuggestExtensions: false

Style/StringLiterals:
  EnforcedStyle: double_quotes

Style/Documentation:
  Enabled: false

Style/NumericPredicate:
  Enabled: false

Layout/EmptyLinesAroundAccessModifier:
  EnforcedStyle: only_before

Layout/IndentationConsistency:
  EnforcedStyle: indented_internal_methods

Naming/FileName:
  Exclude:
    - lib/sidekiq-expiring-jobs.rb

Gemspec/RequireMFA:
  Enabled: false

Bundler/OrderedGems:
  Enabled: false

Minitest/EmptyLineBeforeAssertionMethods:
  Enabled: false
