plugins:
  - rubocop-minitest

AllCops:
  TargetRubyVersion: 3.2
  NewCops: enable
  SuggestExtensions: false

Style/StringLiterals:
  EnforcedStyle: double_quotes

Style/Documentation:
  Enabled: false

Style/NumericPredicate:
  Enabled: false

Style/SymbolArray:
  EnforcedStyle: brackets

Layout/EmptyLinesAroundAccessModifier:
  EnforcedStyle: only_before

Layout/IndentationConsistency:
  EnforcedStyle: indented_internal_methods

Naming/FileName:
  Exclude:
    - lib/sidekiq-expiring-jobs.rb

Metrics:
  Enabled: false

Gemspec/RequireMFA:
  Enabled: false

Bundler/OrderedGems:
  Enabled: false

Minitest/EmptyLineBeforeAssertionMethods:
  Enabled: false
