AllCops:
  TargetRubyVersion: 2.7
  NewCops: enable
  SuggestExtensions: false

Style/StringLiterals:
  EnforcedStyle: double_quotes

Style/Documentation:
  Enabled: false

Naming/FileName:
  Exclude:
    - lib/sidekiq-expiring-jobs.rb

Gemspec/RequireMFA:
  Enabled: false

Bundler/OrderedGems:
  Enabled: false
